### ISSUE TITLE
Socket.io - Client not Receiving Message in Room

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/ValksMatchMaker#4]
## Issue
Both clients are connected to the same room, but they are not receiving the "test" message.
https://github.com/valkyrienyanko/ValksMatchMaker/blob/f98bb89d20bcd4f4d229170598d6031cf8a12f23/server.js#L45-L48

This may be because the test message is sent too soon, but then again that's why I added await calls to every statement.

## Steps to Reproduce
1. Follow steps in [README.md](https://github.com/valkyrienyanko/ValksMatchMaker/blob/master/README.md) to setup app.
2. Open up 2 clients in your browser.
3. Set client one as a male with whatever name you want.
4. Set client two as a female with whatever name you want.
5. Both clients will be redirected to the chat.html page.
6. You should see the words "mytest" in dev console in browser but you don't.

**Comment by arctfoxx** [comment]
I don't think that `Socket#to()#emit()` returns a `Promise`, so `await` will do nothing if that is the case. If it is the case that you're sending the message too soon, what you want to do is the create a handshake, i.e. Client says "I want to start", Server replies with "Okay, join this room please", and the Client replies with, "Got it, I've done that now" and emit your messages after that handshake has been completed.

**Comment by valkyrienyanko** [comment]
> I don't think that `Socket#to()#emit()` returns a `Promise`, so `await` will do nothing if that is the case. If it is the case that you're sending the message too soon, what you want to do is the create a handshake, i.e. Client says "I want to start", Server replies with "Okay, join this room please", and the Client replies with, "Got it, I've done that now" and emit your messages after that handshake has been completed.

Earlier I found out that socket.io does not support async, sorry should have posted that here when I found out.

**Comment by valkyrienyanko** [comment]
The problem was do to switching pages, the sockets would disconnect then connect as 2 new sockets disregarding all the information they ever submitted.
